FROM postgres:11.18-bullseye

ENV GOSU_VERSION 1.10

RUN apk add --update iputils
RUN apk add --update htop

# COPY ./setup-reader.sh /docker-entrypoint-initdb.d
COPY ./docker-entrypoint.sh /docker-entrypoint.sh

RUN chmod +x /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["gosu", "postgres", "postgres"]