FROM postgres:11.18-bullseye

# Update packages to install iputils-ping
RUN apt-get update && apt-get install iputils-ping -y && apt-get clean

COPY ./docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh

# https://stackoverflow.com/a/70040212
COPY ./configure-rw-postgres.sql /docker-entrypoint-initdb.d/configure-rw-postgres.sql

ENTRYPOINT ["/docker-entrypoint.sh"]
# gosu is already installed on the postgress:11.18 Docker image
CMD ["gosu", "postgres", "postgres"]