FROM postgres:13.18-bullseye

# Install iputils-ping so the Reader can ping the Writer
RUN apt-get update && apt-get install iputils-ping -y && apt-get clean

COPY ./docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh

# https://stackoverflow.com/a/70040212
COPY ./configure-rw-postgres.sql /docker-entrypoint-initdb.d/configure-rw-postgres.sql

ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["gosu", "postgres", "postgres"]