services:

  nginx_reverse_proxy:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: example_lambda_nginx_reverse_proxy:07
    container_name: nginx-reverse-proxy07
    volumes:
    - ./templates:/etc/nginx/templates
    ports:
    - "8000:80"
    environment:
    - NGINX_HOST=foobar.com
    - NGINX_PORT=80
    networks:
      - frontend
      - backend

  lambda1:
    # see https://docs.docker.com/reference/compose-file/build/
    build:
      context: .
    # name build image for re-use (see https://github.com/docker/compose/releases/tag/1.6.0)
    image: example_lambda:07
    command: run_lambda1
    ports:
      - "127.0.0.1:9001:8080"
    networks:
      - backend

  lambda2:
    image: example_lambda:07
    command: run_lambda2
    ports:
      - "127.0.0.1:9002:8080"
    depends_on:
      - lambda1
    networks:
      - backend

networks:
  frontend:
  backend:
