FROM postgres:10.23-bullseye

# Install iputils-ping so the Reader can ping the Writer
# Install htop to interactively monitor the system in real-time
RUN apt-get update && apt-get install iputils-ping htop -y && apt-get clean

COPY ./docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["gosu", "postgres", "postgres"]