FROM postgres:9.6-alpine

ENV GOSU_VERSION 1.10

# Install the gosu binary to execute the postgres as root
ADD ./gosu /usr/bin/
RUN chmod +x /usr/bin/gosu

# Install iputils-ping so the Reader can ping the Writer
RUN apk add --update iputils

# Install htop to interactively monitor the system in real-time
RUN apk add --update htop

COPY ./docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["gosu", "postgres", "postgres"]