services:
  db:
    image: postgres:17.8-bookworm
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=fastapi_user
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_DB=fastapi_demo
    ports:
      - 5432:5432
    networks:
      default:
        aliases:
          - pg_cluster

volumes:
  pg_data:
