services:
  pg_writer:
    build:
      dockerfile: ./Dockerfile.writer
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=pg17demo
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_DB=pg17demo
      - PG_REP_USER=rep_user
      - PG_REP_PASSWORD=use4replication
      - PUB_SUB_USER=pub_user
      - PUB_SUB_PASSWORD=use4pubsub
    networks:
      default:
        aliases:
          - pg_cluster

  pg_reader:
    build:
      dockerfile: ./Dockerfile.reader
    environment:
      - POSTGRES_USER=pg17demo
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_DB=pg17demo
      - PG_REP_USER=rep_user
      - PG_REP_PASSWORD=use4replication
      - PG_WRITER_HOST=pg_writer
    networks:
      default:
        aliases:
          - pg_cluster

  pg_subscriber:
    build:
      dockerfile: ./Dockerfile.subscriber
    volumes:
      - sub_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=pg17demo
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_DB=pg17demo
      - PUB_SUB_USER=pub_user
      - PUB_SUB_PASSWORD=use4pubsub
      - PG_PUBLISHER_HOST=pg_writer
    command:
      - "postgres"

volumes:
  pg_data:
  sub_data:
